name: Format
on:
  pull_request:
    branches: [master]
jobs:
  format:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm run format
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: apply auto formatting
          branch: ${{ github.head_ref }}