name: Tests

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.14.0
      options: --shm-size=2g
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run tests
      run: npm run test
